version: 2
jobs:
  build:
    working_directory: ~/circledock
    docker:
      - image: circleci/ruby
    environment:
      - OWNER: asupara7
      - IMAGE1_NAME: circledock

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t ${OWNER}/${IMAGE1_NAME}:latest .
      - run:
          name: Save image
          command: docker image save ${OWNER}/${IMAGE_NAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./docker-image.tar
      - run:
          name: Load image from tar
          command: docker load -i ./docker-image.tar
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - restore_cache:
          key: job-medley-app-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle install --jobs=4 --path=vendor/bundle
      - save_cache:
          key: job-medley-app-{{ checksum "Gemfile.lock" }}
          paths:
            vendor/bundle
      - run:
          name: Run tests
          command: |
            bundle exec rake
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker tag ${OWNER}/${IMAGE1_NAME}:latest ${OWNER}/${IMAGE1_NAME}:${CIRCLE_SHA1}
              docker push ${OWNER}/${IMAGE1_NAME}
            fi
