version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/ruby

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              gettext
            pip install \
              docker-compose==1.12.0 \
              ansible
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: provision with ansible
          command: |
            cd ansible \
            ansible-playbook site.yml
      - restore_cache:
          key: job-medley-app-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle install --jobs=4 --path=vendor/bundle
      - save_cache:
          key: job-medley-app-{{ checksum "Gemfile.lock" }}
          paths:
            vendor/bundle
      - run:
          name: Run tests
          command: |
            bundle exec rake
