version: 2
jobs:
  build:
    working_directory: ~/circledock
    docker:
      - image: circleci/ruby
    environment:
      - OWNER: asupara7
      - IMAGE1_NAME: circledock

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: sudo apt-get install -y ansible
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/${IMAGE1_NAME}:latest.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/${IMAGE1_NAME}:latest.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=${IMAGE1_NAME}:latest -t ${IMAGE1_NAME}:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/${IMAGE1_NAME}:latest.tar ${IMAGE1_NAME}:latest
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/${IMAGE1_NAME}:latest.tar
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: provision with ansible
          command: |
            cd ansible
            ansible-playbook site.yml
      - restore_cache:
          key: job-medley-app-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle install --jobs=4 --path=vendor/bundle
      - save_cache:
          key: job-medley-app-{{ checksum "Gemfile.lock" }}
          paths:
            vendor/bundle
      - run:
          name: Run tests
          command: |
            bundle exec rake
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker tag ${IMAGE1_NAME}:latest "${OWNER}/${IMAGE1_NAME}:${CIRCLE_SHA1}"
              docker push "${OWNER}/${IMAGE1_NAME}:${CIRCLE_SHA1}"
            fi
